name: Dummy action

on:
  pull_request:
    branches:
      - master
      - main
      - develop
      - release/*

jobs:
  Dummy-action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a dummy action required so we can enforce PRs to have up-to-date branches. GitHub requires an action to enable that check, so here we are."